language: python

python:
  - "3.7"

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  # Get miniconda and install it
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  # Make conda always say yes
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Print out conda config info for debugging purposes
  - conda info -a

  # Create the new environment
  - conda env create -f environment.yml
  # Swap to new env
  - source activate kcwidrp
  # Install the new build. Does NOT use "pip install kcwidrp" so that we get new
  # changes
  - pip install .

  # Old commands:
  # - pip install Cython
  # - pip install -r requirements.txt -c constraints.txt

script:
  - pytest