language: python

python:
  - "3.7"

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda env create -f environment.yml
  - source activate kcwidrptest
  - pip install .
  # - pip install Cython
  # - pip install -r requirements.txt -c constraints.txt

script:
  - python setup.py install
  - pytest