language: python

python:
  - "3.7"

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - pip install Cython
  - pip install -r requirements.txt -c constraints.txt

script:
  - python setup.py install
  - pytest