name: kcwidrp
dependencies:
  - python=3.7
  - scikit-image~=0.16.2
  - astropy~=4.0 
  - conda-forge::ccdproc~=2.2.0
  - numpy~=1.20
  - scipy~=1.4.1
  - pyerfa
  - bokeh~=2.0.0
  - jinja2~=3.0.3
  - psutil~=5.7.0
  - pandas~=1.0.3
  - matplotlib~=3.1.3
  - conda-forge::selenium
  - conda-forge::geckodriver
  - conda-forge::firefox
  - conda-forge::phantomjs
  - astropy::pyregion
  - requests
  - pytest~=5.4.1
  - cython
  - setuptools~=46.1.1
  - pip
  - pip:
    - ref_index~=1.0
    - keckdrpframework