{% set version = "0.1.11dev0" %}

package:
  name: kcwidrp
  version: {{ version }}

requirements:
  host:
    - python=3.7
    - pip
  run:
    - python

build:
  script: python -m pip install .
  
source:
  - url: https://files.pythonhosted.org/packages/8f/ef/0d18d8d7c172420b3211f960961599acb7ec481b85f661810afed2813573/kcwidrp-0.0.1.dev0.tar.gz
    sha256: 48f61517e153706bacc3691eb47b660fbc4d0a3a7efc910421325b7d91103acb
    md5: 52a8acc239d17fc49c79f9bb6fd32d26
    folder: kcwidrp

about:
  home: https://github.com/Keck-DataReductionPipelines/KCWI_DRP.git
  license: BSD 3-Clause
  summary: 'KCWI Data Reduction Pipeline'
  doc_source_url: https://kcwi-drp.readthedocs.io/en/latest/